+: {Type: Folder, DefaultTypes: [Task, Folder]}
Id: Misc

OnGoing .IT:
  Id: IT
  OnGoing .Environment configuration:
    Id: EnvConfig
    Details:
      SW Installations, configuration, etc.
  OnGoing .Git setups:
    Id: Git
    Blocked .Create a new repository after the cleanups:
      +: {CreatedBy: Bobi, CreatedAt: 20260420 T 133138, By: Bobi, Tags: [CSVDONE], Estimation: "30", RemTime: "30"}
      DependsOn: -->Tasks\Management\.."OCWSPhase1".."Clean up the files we are publishing"<
      
OnGoing .BusinessAnalysis:
  Id: BA
  Details:
    Business analysis related - e.g. requirement writing, discussions, etc.
  .F2ToolsExtension:
    Id: F2Tools
    InProgress .QueryDescription based CSV report generation:
      Id: QueryBasedCSV
      +: {CreatedBy: Bobi, CreatedAt: 20260513 T 004711, By: [Bobi, Hana]}
      Details:
        - Work into: -->Documents\Requirements\F2ToolsExtension\..Phase2..QueryBasedCSV<
        - Reach the ReadyForDev status (including a review with Hana)
      Done .Create Draft:
        +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161748, By: Bobi, Tags: [CSVTODO], Estimation: 120, RemTime: 0}
      TODO .Review with Hana:
        +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161808, By: [Bobi, Hana], Tags: [CSVTODO], Estimation: 20, RemTime: 20}
    InProgress .F2Link related upgrades:
      Id: F2LinkUpgrades
      +: {CreatedBy: Bobi, CreatedAt: 20260520 T 153759, By: [Bobi,Hana], Estimation: 120, RemTime: 20}
      Details:
        - work into -->Documents\Requirements\F2ToolsExtension\..Phase2..F2LinkUpgrades<
        - Reach the ReadyForDev status (including a review with Hana)
      Done .Create Draft:
        +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161748, By: Bobi, Tags: [CSVTODO], Estimation: 120, RemTime: 0}
      TODO .Review with Hana:
        +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161808, By: [Bobi, Hana], Tags: [CSVTODO], Estimation: 20, RemTime: 20}
    Done .Text Output support:
      Id: TextOutput
      +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161853, By: Bobi, Tags: [CSVTODO], Estimation:, RemTime:}
      Details:
        Work into -->Documents\Requirements\F2ToolsExtension\..Phase2..TextOutput<

OnGoing .Health:
  TODO .Create an an analysis about the effects of consuming various sugars:
    +: {CreatedBy: Bobi, CreatedAt: 20260417 T 122654, By: [Bobi Hana], Tags: [CSVDONE], Estimation: "60", RemTime: "60"}
    Details:
      Include:
        Sucrose vs dextrose:
        Sugar crash/spike:
          - what are the symptoms of spike/crash
          - how to avoid it
          - adverse effects short long term:
            - how to "heal" them          
          - how to combine macronutrients to avoid spike (e.g. fats)
        Difference in between females and males:
        How much of dextrose and sucrose should we include in our diets:
          - Taking into account that we have sensitive digestion AND surcose can stay in your guts without being digested longer
        What happens after the sugars (dextrose + fructose) enter the bloodstream:
          - liver (glycogen) storage
          - fructose processing
          - insulin and fat storage
          - muscle storage
        Eating various of amounts:
        Activities before/after eating:
          - Walk after - how much it helps
          - Eating on "starved" state:
            - sugar spike?
  Done .Create a daily health tracking template to monitor sleep quality, bowel movements, mood, nutrition, hydration, and physical activity.:
    +: {CreatedBy: Hana, CreatedAt: 20260421 T 174216, By: Hana, Tags: [CSVDONE], Estimation: 60, RemTime: 0}
  OnGoing .Do health log and daily reviews:
    +: {CreatedBy: Bobi, CreatedAt: 20260428 T 131144, By: Hana, Tags: [CSVDONE]}
    Details:
      - analyse Health through Garmin data
      - review exercise schedule
      - stream it      
  OnGoing .Do weekly health related planning:
    +: {CreatedBy: Bobi, CreatedAt: 20260504 T 135831, By: Bobi, Tags: [CSVDONE], Estimation:, RemTime:}
    Details:
      Perform the followings:
        OnGoing .Schedule Health Analysis sessions(Live):
          Details:
            Basically performing the -->Tasks\Miscellaneous\.."Health".."Do health log and daily reviews"< 
        TODO .Schedule exercises and include baba in the morning after waking up and evening before sleeping:
          Details: 
            - We can start preschedule for a week period
            - Include goals what we want to acheive in a month, 3 month, 6 month
        TODO .Schedule body measurement:

  .Schedules:
    TODO .Schedule Health Analysis (Live):
      Details: 
      - Better bidaily (morning before waking up and evening (sleep hygiene period)
      - To be done for Hana, Robi ad Baba

<EOF>: #Write above and do not delete this line please; without this, in VS Code editor if every Item is folded and you want to add something after the last one, you had to unfold the last one, navigate to the end of it, add a line and then go back and fold the (former) last one.  (EOF = End of File)