+: {Type: Folder, DefaultTypes: [Task, Folder]}
Id: Misc

OnGoing .IT:
  Id: IT
  OnGoing .Environment configuration:
    Id: EnvConfig
    Details:
      SW Installations, configuration, etc.
  OnGoing .Git setups:
    Id: Git
    Blocked .Create a new repository after the cleanups:
      +: {CreatedBy: Bobi, CreatedAt: 20260420 T 133138, By: Bobi, Tags: [CSVDONE], Estimation: "30", RemTime: "30"}
      DependsOn: -->Tasks\Management\.."OCWSPhase1".."Clean up the files we are publishing"<
      
OnGoing .BusinessAnalysis:
  Id: BA
  Details:
    Business analysis related - e.g. requirement writing, discussions, etc.
  .F2ToolsExtension:
    Id: F2Tools
    InProgress .QueryDescription based CSV report generation:
      Id: QueryBasedCSV
      +: {CreatedBy: Bobi, CreatedAt: 20260513 T 004711, By: [Bobi, Hana]}
      Details:
        - Work into: -->Documents\Requirements\F2ToolsExtension\..QueryBasedCSV<
        - Reach the ReadyForDev status (including a review with Hana)
      Done .Create Draft:
        Id: CreateDraft
        +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161748, By: Bobi, Tags: [CSVTODO], Estimation: 120, RemTime: 0}
      InProgress .Review with Hana:
        Id: Review
        +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161808, By: [Bobi, Hana], Estimation: 20, RemTime: 10}
      OnGoing .Handover and changes during implementation:
        Id: Handover
        +: {CreatedBy: Bobi, CreatedAt: 20260527 T 153932, By: [Bobi, Hana]}
    InProgress .F2Link related upgrades:
      Id: F2LinkUpgrades
      +: {CreatedBy: Bobi, CreatedAt: 20260520 T 153759, By: [Bobi,Hana], Estimation: 120, RemTime: 20}
      Details:
        - work into -->Documents\Requirements\F2ToolsExtension\..F2LinkUpgrades<
        - Reach the ReadyForDev status (including a review with Hana)
      Done .Create Draft:
        +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161748, By: Bobi, Tags: [CSVTODO], Estimation: 120, RemTime: 0}
      TODO .Review with Hana:
        +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161808, By: [Bobi, Hana], Tags: [CSVTODO], Estimation: 20, RemTime: 20}
    Done .Text Output support:
      Id: TextOutput
      +: {CreatedBy: Bobi, CreatedAt: 20260520 T 161853, By: Bobi, Tags: [CSVTODO], Estimation:, RemTime:}
      Details:
        Work into -->Documents\Requirements\F2ToolsExtension\..TextOutput<

OnGoing .Health:
  InProgress .Health planning W20260608:
    +: {CreatedBy: Bobi, CreatedAt: 20260608 T 191459, By: Bobi}
    Details:
      Food
      Gym
      Dandar Bath - Thursday?
    Workspace:
      Food:
        Tuesday-Friday:
          Afrikai harcsa
          Chicken breast w sauces
          Luncheon meat with boc choy
          Chicken soup
          Pork soup          
      Supplements:
        Details: -->..."Hana to make supplements plan"<
        WorkSpace:
          Supplement plan:
            After waking up:
              - L-Glutamin 5g
              - L- Citrolline 2g
              - 5HTP pill
            Breakfast:
              - Omega 3 1 pill
            Lunch:
              - Omega 3 1 pill
              - Creatine 5 g
            Dinner:
              - L-Glutamin 5 g
              - Collagen 5g
              - NAC 1 pill
      Gym:
        Target is every day
      Cardio:
        One day run, then hiit, then rest
    Done .Hana to make supplements plan:
      +: {CreatedBy: Bobi, CreatedAt: 20260608 T 221507, By: Hana}
      Details:
        About each supplement:
          Id:
          Quantity:
          When:
            Details: at what time of the day, before/after meals, etc.
          Benefits:
        Group them if possible - such as "morning", "before meal", etc.:          
        Per person:
    InProgress .Hana to schedule it own in google Calendar:
      +: {CreatedBy: Hana, CreatedAt: 20260610 T 135521, By: Hana, Tags: [CSVTODO], Estimation: 30m, RemTime: 30m}
      Done .Activity has been scheduled in (hanakovacs42@gmail.com) calendar:
      Done .Schedule supplements:

  TODO .Create an an analysis about the effects of consuming various sugars:
    +: {CreatedBy: Bobi, CreatedAt: 20260417 T 122654, By: [Bobi Hana], Tags: [CSVDONE], Estimation: "60", RemTime: "60"}
    Details:
      Include:
        Sucrose vs dextrose:
        Sugar crash/spike:
          - what are the symptoms of spike/crash
          - how to avoid it
          - adverse effects short long term:
            - how to "heal" them          
          - how to combine macronutrients to avoid spike (e.g. fats)
        Difference in between females and males:
        How much of dextrose and sucrose should we include in our diets:
          - Taking into account that we have sensitive digestion AND surcose can stay in your guts without being digested longer
        What happens after the sugars (dextrose + fructose) enter the bloodstream:
          - liver (glycogen) storage
          - fructose processing
          - insulin and fat storage
          - muscle storage
        Eating various of amounts:
        Activities before/after eating:
          - Walk after - how much it helps
          - Eating on "starved" state:
            - sugar spike?
  Done .Create a daily health tracking template to monitor sleep quality, bowel movements, mood, nutrition, hydration, and physical activity.:
    +: {CreatedBy: Hana, CreatedAt: 20260421 T 174216, By: Hana, Tags: [CSVDONE], Estimation: 60, RemTime: 0}
    Result: -->CurrentWork\Hana\HealthTF2P\Healthlogs\.HealthLog20260606Hana<
  OnGoing .Do health log and daily reviews:
    +: {CreatedBy: Bobi, CreatedAt: 20260428 T 131144, By: Hana, Tags: [CSVDONE]}
    Details:
      - analyse Health through Garmin data
      - review exercise schedule
      - stream it      
  OnGoing .Do weekly health related planning:
    +: {CreatedBy: Bobi, CreatedAt: 20260504 T 135831, By: Bobi, Tags: [CSVDONE], Estimation:, RemTime:}
    Details:
      Perform the followings:
        InProgress .Analyse Health Data:
          +: {CreatedBy: Hana, CreatedAt: 20260621 T 004355, By: Hana, Tags: [CSVTODO], Estimation: 180m, RemTime: 180m}       
        OnGoing .Schedule Health Analysis sessions:
          Details:
            Basically performing the -->Tasks\Miscellaneous\.."Health".."Do health log and daily reviews"< and creating schedule for the next week:
          Results: 
            20260624: https://connect.garmin.com/app/calendar June 25 to Jun29
        TODO .Schedule exercises and include baba in the morning after waking up and evening before sleeping:
          Details: 
            - We can start preschedule for a week period
            - Include goals what we want to acheive in a month, 3 month, 6 month
        TODO .Schedule body measurement:
  InProgress .Create health-log tracking requirements:
    +: {CreatedBy: Bobi, CreatedAt: 20260608 T 192920, By: Bobi}
    Details:
      - Collect the use cases - what do we want to use them for; don't do it too formally though
      - Collect what data we want to collect:
        - Results:
          - Mood
          - Farting/Burping/Poop
          - Fights
        - Possible causes:
          - Food we ate:
            - \"fancy" stuff: suspicious spices (garlic, onion, csípős),
            - Veggies:
            - Resistant starch
            - Fatty/non            
          - Gym, etc.
          - Anything "worth mentioning" - so there should be a field for this
          - Drugs:
            - Both supplements and non-supplements          
    InProgress .Collect initial ideas:
      +: {CreatedBy: Bobi, CreatedAt: 20260609 T 143822, By: [Bobi, Hana], Estimation: 15m, Remaining: 15}
      Workspace:
        What we want with all this data collection:
          Final goals:
            Better mood and general physical condition so that we can be jolly happy all the time
          SubGoals:
            - Develop a knowledge-base about how to live the most happy life, understanding that health plays a big role:
              - a balance need to be found, because both:
                - health plays a big role in one's ability to be happy
                - one can't spend all his/her time on health-improvement taks; all work no play makes Jack a dull boy.
              - what and how to eat, exercise, take ds to find the balance
              - identify the areas which matter (eating timing, spices, macro-micro nutrients, exercise heavyness, frequency, timing, etc.)
              - identify what events cause what events - e.g. late eating causes bad mood and digestion next day
            - Create reports:
              - Detailed "completed exercises" reports, e.g. how many reps in what exercises (like bench-press)
          The followings should be logged:
            - an entry from one of the below LogEntry descendants
            - about each event the specific class is about
            - done:
                when: 1-2 times per day OR right after the event OR next morning/before bed
                how: do not spend too much time on it - so 20 mins ideally per day in total for 2 people
            - snippets should be created
          Classes:
            class .LogEntry:
              Inherits: StandardItem
              string UserName:       
              DateTime Time:
                Details: the time of the event; 
              string NotableThings:
                Details: anything notable for the event          
            class .SupplementLog:
              Inherits: LogEntry
              string[] What:
            class .MealLog:
              Inherits: LogEntry
              string .Description:
              Levels .HungerBefore:
              Levels .HungerAfter:
              Levels .Amount:
              GarminAnalysis .GarminPhotoAnalysis:
                Details: type to be defined later
              MoodLog .MoodBefore:
              MoodLog .MoodAfter:                
            class .PoopikaLog:
              Inherits: LogEntry
              PoopikaType .PType:
            class .GarminAnalysis:
              Inherits: Item
              string .URL:
            class .MoodLog:
              Inherits: LogEntry
              Duration .PeriodLengthInHrs:
                Details:
                  The length of time (starting from Time) for which the log is recorded; average values.
              Levels .Irritability:
              Levels .Drowsiness:
              Levels .Foggyness:
              string .TummyGassesFeel:
              Levels .Bloatedness:
              Levels .Burping:
              Levels .Farting:
              Levels .Headache:
              Levels .Hornyness:
            class .ExerciseLog:
              Inherits: LogEntry
              string .Category:
                Details:
                  Weights, Running, Walking, Hiking, Stretching, Sauna
              Duration .Length:
              Levels .Intensity:
            class .DLog:
              Inherits: LogEntry
              string Kind:
                Details:
                  W, M, K, C, V, etc.
              Levels Intensity:
                Details:
                  The effects of it - how much it was felt                
  OnGoing .Create food schedule for the next week:
    Details: 
      - Fish 3x a week
      - One vegeterian day for Hana
      - Take into consideration the time of month for menstrual cycle
      - Focus on Robis Health
  OnGoing .Schedule and estimate activity for a week:
    Details:
      - Activity should be based on the physical symptoms
  EstTODO .Research kidney-saving protocol:
    +: {CreatedBy: Bobi, CreatedAt: 20260725 T 204053, By: [Hana, Bobi], Tags: [TL, Private], Estimation: , RemTime: , Importance: 6-Extreme}
    Details:
      - include:
        - low blood pressure effects
        - diet - what to eat/avoid
        - exercises
        - water
        - salt
        - sickle cell trait effects      
  .Schedules:
    Done .Schedule Health Analysis (Live):
      +: {CreatedBy: Hana, CreatedAt: 20260609 T 142824, By: Hana, Tags: [CSVTODO], Estimation: 40m, RemTime: 40m}
      Details:
        Hana to designed schedule for food, mobility and sleep for both and to share the results with Bobi tomorrow Live
      Results: -->Tasks\Miscellaneous\.."Health".."Create health-log tracking requirements"<

InProgress .Create incentivisation system baseline:
    +: {CreatedBy: Bobi, CreatedAt: 20260614 T 192842, By: Bobi, Tags: [CSVTODO], Estimation:, RemTime:}
    Workspace:
      First idea:
        # - points 1p = 1 "effectively spent minute on important task":
        #   - important task: something which we'd likely prioritize as such on a prioritization meeting
        #   - effectively: concentrating on the Task, not e.g. browsing, talking, chatting or fiddling with some unimportant details of it
        - incentives:            
            # .DailyDishwashing:
            #   Details:
            #     At each checkpoint - e.g. end of the day - the decision is made about the dishwashing scheule:
            #     - checkpoint meeting can be triggered by any of the participants at or after the scheduled time (currently at standup time)
            #     - rule ideas:
            #       - the one collecting less points is the one washing the dishes before going to bed
            .EnforceImportantTask:
              Details:
                - On the threat of a number of dishwashing (one-one day-one week) one needs to perform a Task:                  
                  - first n warnings should be issued
                  - if the Task is still not completed after the warnings, the consequences can be triggered - e.g. next x day dishwashing.:
                - If a Task is like this, the concrete rules (how many warnings, what is the punishment exactly) should be mentioned in its Comments property
    TODO .Move the idea from the above workspace to its correct place:
      +: {CreatedBy: Bobi, CreatedAt: 20260614 T 195929, By: Bobi, Tags: [CSVTODO], Estimation:, RemTime:}
      Details:
        - maybe processes? yep. But where - that's the task.

    NEXT .Finalize and review it:
      +: {CreatedBy: Bobi, CreatedAt: 20260609 T 143837, By: [Hana, Bobi]}
    
<EOF>: #Write above and do not delete this line please; without this, in VS Code editor if every Item is folded and you want to add something after the last one, you had to unfold the last one, navigate to the end of it, add a line and then go back and fold the (former) last one.  (EOF = End of File)