Link ::= "-->" <FilePath> <YamlPath> "<"
FilePath ::= (<FilePathPart> "\\")*
FilePathPart ::= +<AllowedFileCharacters>+
YamlPath ::= <YamlPathPart>*
YamlPathPart ::= "." (<PropertyIdentifier> | ("." <ItemIdentifier>))
PropertyIdentifier ::= <IdentifierChar>+
ItemIdentifier ::= <ItemIdentifierWithId> | <ItemIdentifierWithGUID> | <ItemIdentifierWithSummary>
ItemIdentifierWithId ::= <IdentifierChar>+
ItemIdentifierWithGUID ::= "{" <GUID> "}"
ItemIdentifierWithSummary ::= '"' <Text> '"'

IdentifierChar ::= // so the characters: A-Za-z0-9_-