CustomColoringJSONPath: colors.json
SourceFolder: ..\..\
OutputFolder: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss
Files:
- SourceFilePath:                                                 ..\..\CurrentWork\Bobi\Workspace.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\CurrentWork\Bobi
- SourceFilePath:                                                 ..\..\CurrentWork\Bobi\TasksToBeSorted.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\CurrentWork\Bobi
- SourceFilePath:                                                 ..\..\CurrentWork\Bobi\StandupReports.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\CurrentWork\Bobi
- SourceFilePath:                                                 ..\..\CurrentWork\Hana\Workspace.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\CurrentWork\Hana
- SourceFilePath:                                                 ..\..\CurrentWork\Hana\TasksToBeSorted.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\CurrentWork\Hana
- SourceFilePath:                                                 ..\..\CurrentWork\Hana\StandupReports.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\CurrentWork\Hana
- SourceFilePath:                                                          ..\..\BusinessClasses.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\
- SourceFilePath:                                                          ..\..\Documents\F2YamlSpecification\F2Yaml.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Documents\F2YamlSpecification
- SourceFilePath:                                                          ..\..\Documents\Requirements\TheF2Tool.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Documents\Requirements
- SourceFilePath:                                                          ..\..\Documents\Requirements\Website.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Documents\Requirements
- SourceFilePath:                                                          ..\..\Documents\Requirements\F2ToolsExtension.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Documents\Requirements
- SourceFilePath:                                                          ..\..\Documents\Requirements\F2FinanceHelper.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Documents\Requirements
- SourceFilePath:                                                          ..\..\MeetingMinutes\Plannings.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\MeetingMinutes
- SourceFilePath:                                                          ..\..\MeetingMinutes\StandupReports.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\MeetingMinutes
- SourceFilePath:                                                          ..\..\MeetingMinutes\Retrospectives.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\MeetingMinutes
- SourceFilePath:                                                          ..\..\Reports\Archive\OCWSPhase1.csv
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Reports\Archive  
- SourceFilePath:                                                          ..\..\Reports\Archive\TaskListDoneTasks.csv
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Reports\Archive  
- SourceFilePath:                                                          ..\..\Reports\TaskListTasks.csv 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Reports
  #ColumnNames: [Status, Estimation,By, RemTime, IdLink]
- SourceFilePath:                                                          ..\..\Reports\DevTasks.csv 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Reports
- SourceFilePath:                                                          ..\..\Reports\Before1stPostTasks.csv 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Reports
  #ColumnNames: [Status, Estimation,By, RemTime, IdLink]  
- SourceFilePath:                                                          ..\..\System\Types.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\System
- SourceFilePath:                                                          ..\..\System\Types\Processes.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\System\Types
- SourceFilePath:                                                          ..\..\System\Types\Queries.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\System\Types
- SourceFilePath:                                                          ..\..\System\Types\Workspaces.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\System\Types
- SourceFilePath:                                                          ..\..\System\Types\Yaml.Rendering.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\System\Types  
- SourceFilePath:                                                          ..\..\Tasks\PublicRelations.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\
- SourceFilePath:                                                          ..\..\Tasks\Documents.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\
- SourceFilePath:                                                          ..\..\Tasks\Management.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\
- SourceFilePath:                                                          ..\..\Tasks\Processes.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\
- SourceFilePath:                                                          ..\..\Tasks\Website.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\
- SourceFilePath:                                                          ..\..\Tasks\Software\TheF2Tool.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\Software\
- SourceFilePath:                                                          ..\..\Tasks\Software\F2ToolsExtension.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\Software\
- SourceFilePath:                                                          ..\..\Tasks\Software\F2FinanceHelper.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\Software\  
- SourceFilePath:                                                          ..\..\Tasks\Software\F2FileToHtmlConverter.yml 
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks\Software\  
  
- SourceFilePath:          ..\..\Documents\WebsiteContent\Summary.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read
- SourceFilePath:          ..\..\Documents\WebsiteContent\Articles.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read
- SourceFilePath:          ..\..\Documents\WebsiteContent\DeepDive.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read
- SourceFilePath:          ..\..\Documents\WebsiteContent\Updates.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read
- SourceFilePath:          ..\..\Documents\WebsiteContent\Watch\Watch.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Watch
- SourceFilePath:          ..\..\Documents\WebsiteContent\Contact\Contact.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Contact
- SourceFilePath:          ..\..\Documents\WebsiteContent\Support\Support.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Support  
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\CurrentWork.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\LearnToDive.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive  
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\LearnToDive\Overview.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\LearnToDive\
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\LearnToDive\Syntax.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\LearnToDive\  
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\ClassDescriptions.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\Documents.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\MeetingMinutes.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss  
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\Tasks.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\System.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\Documents\F2YamlSpecification.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Documents
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\Documents\Requirements.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Documents
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\System\Types_Description.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\System\
- SourceFilePath:               ..\..\Documents\WebsiteContent\DeepDive\TheAbyss\Tasks\Software.yml
  TargetFolderPath: ..\..\..\theforty2project.org\content\Read\DeepDive\TheAbyss\Tasks

