+: { Type: Folder, DefaultTypes: [ Folder, Task ] }

TODO .Placeholder:_ Implement:
  Details:
    Try it with Codex (or similar) first, at least the trivial functionalities
  
<EOF>: #Write above and do not delete this line please; without this, in VS Code editor if every Item is folded and you want to add something after the last one, you had to unfold the last one, navigate to the end of it, add a line and then go back and fold the (former) last one. (EOF = End of File)